### ISSUE TITLE
Just wanted to ask

### ISSUE THREAD

**Issue by JesterlJoker** [Y-samp/Y-Core#3]
Are you still going to continue on developing this? It's not that I'm using it, It's just that I learned more on YCore and YRP.

**Comment by Misiur** [comment]
Yup, but only after I finish the amx debugger (at least the core api), so hopefully soon.

**Comment by JesterlJoker** [comment]
ahhh, good to know... hope to see some more updates soon. Can't wait to see more of the YSI library in action...
